<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.automation.testCases.Login.EmailLoginTest" tests="4" time="0.000" ignored="4" failures="0" timestamp="18 Jun 2019 06:17:05 GMT" skipped="2" hostname="DESKTOP-CCGNHEN" errors="2">
  <testcase name="fromStartpageLoginWitDdifferentWrongCredential" time="0.000" classname="com.automation.testCases.Login.EmailLoginTest">
    <skipped/>
  </testcase> <!-- fromStartpageLoginWitDdifferentWrongCredential -->
  <testcase name="fromStartpageLoginWitDdifferentWrongCredential" time="0.000" classname="com.automation.testCases.Login.EmailLoginTest">
    <skipped/>
  </testcase> <!-- fromStartpageLoginWitDdifferentWrongCredential -->
  <testcase name="fromStartpageLoginWithWrongCredentialSE" time="0.000" classname="com.automation.testCases.Login.EmailLoginTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.automation.testCases.Login.EmailLoginTest.fromStartpageLoginWithWrongCredentialSE(EmailLoginTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- fromStartpageLoginWithWrongCredentialSE -->
  <testcase name="fromStartpageLoginWithWrongCredentialSE" time="0.000" classname="com.automation.testCases.Login.EmailLoginTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.automation.testCases.Login.EmailLoginTest.fromStartpageLoginWithWrongCredentialSE(EmailLoginTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- fromStartpageLoginWithWrongCredentialSE -->
  <testcase name="stopAppiumServers" classname="com.automation.config.BaseTest">
    <skipped/>
  </testcase> <!-- stopAppiumServers -->
  <testcase name="stopAppiumServers" classname="com.automation.config.BaseTest">
    <skipped/>
  </testcase> <!-- stopAppiumServers -->
  <testcase name="startAppiumServers" classname="com.automation.config.BaseTest">
    <skipped/>
  </testcase> <!-- startAppiumServers -->
  <testcase name="startAppiumServers" classname="com.automation.config.BaseTest">
    <skipped/>
  </testcase> <!-- startAppiumServers -->
</testsuite> <!-- com.automation.testCases.Login.EmailLoginTest -->
